const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const $=x=>document.getElementById(x);let rows=[];
const esc=v=>{let d=document.createElement('div');d.textContent=v||'';return d.innerHTML};
async function admin(){let{data,error}=await sb.rpc('is_admin');return !error&&data===true}
async function load(){let{data,error}=await sb.rpc('admin_get_coachings');if(error){alert(error.message);return}rows=data||[];$('nc').textContent=rows.length;$('no').textContent=new Set(rows.map(x=>x.owner_id)).size;let b=await sb.from('batches').select('id');$('nb').textContent=b.data?.length||0;render()}
function render(){let q=$('os').value.toLowerCase();let a=rows.filter(x=>`${x.owner_email} ${x.founder_name} ${x.coaching_name} ${x.phone}`.toLowerCase().includes(q));$('ot').innerHTML='<div class="table"><div class="row headrow"><div>Owner/Coaching</div><div>Email</div><div>Phone</div><div>Slug</div><div>Actions</div></div>'+a.map(x=>`<div class="row"><div><b>${esc(x.founder_name||'Owner')}</b><br>${esc(x.coaching_name)}</div><div>${esc(x.owner_email)}</div><div>${esc(x.phone)}</div><div>${esc(x.slug)}</div><div class="actions"><button class="edit" onclick="edit('${x.id}')">Edit</button><button class="danger" onclick="delOwner('${x.owner_id}')">Delete Owner</button></div></div>`).join('')+'</div>';let q2=$('ps').value.toLowerCase();a=rows.filter(x=>`${x.coaching_name} ${x.slug} ${x.phone} ${x.owner_email}`.toLowerCase().includes(q2));$('pt').innerHTML='<div class="table"><div class="row headrow"><div>Coaching</div><div>Owner</div><div>Founder</div><div>Phone</div><div>Actions</div></div>'+a.map(x=>`<div class="row"><div><b>${esc(x.coaching_name)}</b><br>${esc(x.slug)}</div><div>${esc(x.owner_email)}</div><div>${esc(x.founder_name)}</div><div>${esc(x.phone)}</div><div class="actions"><button class="open" onclick="location.href='https://coaching.greatindia.technology/?slug=${encodeURIComponent(x.slug)}'">Open</button><button class="edit" onclick="edit('${x.id}')">Edit</button><button class="danger" onclick="delPage('${x.id}')">Delete</button></div></div>`).join('')+'</div>';$('recent').innerHTML=a.slice(0,8).map(x=>`<p><b>${esc(x.coaching_name)}</b> — ${esc(x.owner_email||'')}</p>`).join('')||'No pages yet'}
function edit(id){let x=rows.find(r=>r.id===id);if(!x)return;$('eid').value=x.id;$('en').value=x.coaching_name||'';$('es').value=x.slug||'';$('ed').value=x.description||'';$('efn').value=x.founder_name||'';$('eds').value=x.founder_designation||'';$('ep').value=x.phone||'';$('ee').value=x.email||'';$('ea').value=x.address||'';$('modal').classList.remove('hide')}
async function delPage(id){if(!confirm('Delete coaching page?'))return;let{error}=await sb.from('coachings').delete().eq('id',id);if(error)alert(error.message);else load()}
async function delOwner(id){if(!confirm('Delete owner and all coaching/batches?'))return;let{error}=await sb.rpc('admin_delete_owner',{target_user_id:id});if(error)alert(error.message);else load()}
$('lf').onsubmit=async e=>{e.preventDefault();let{data,error}=await sb.auth.signInWithPassword({email:$('em').value,password:$('pw').value});if(error){$('lm').textContent='❌ '+error.message;return}if(!await admin()){await sb.auth.signOut();$('lm').textContent='❌ Admin access denied';return}$('login').classList.add('hide');$('app').classList.remove('hide');$('who').textContent=data.user.email;load()};
$('ef').onsubmit=async e=>{e.preventDefault();let p={coaching_name:$('en').value.trim(),slug:$('es').value.trim().toLowerCase(),description:$('ed').value,founder_name:$('efn').value,founder_designation:$('eds').value,phone:$('ep').value,email:$('ee').value,address:$('ea').value};let{error}=await sb.from('coachings').update(p).eq('id',$('eid').value);if(error){$('msg').textContent='❌ '+error.message;return}$('modal').classList.add('hide');load()};
$('x').onclick=()=> $('modal').classList.add('hide');$('os').oninput=render;$('ps').oninput=render;$('lo').onclick=async()=>{await sb.auth.signOut();location.reload()};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(b.dataset.p).classList.add('active')});
(async()=>{let{data:{session}}=await sb.auth.getSession();if(session&&await admin()){$('login').classList.add('hide');$('app').classList.remove('hide');$('who').textContent=session.user.email;load()}})();