const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);let user=null,coaching=null,authMode='login';const $=id=>document.getElementById(id);
function show(id){['home','auth','dash','public'].forEach(x=>$(x).classList.add('hidden'));$(id).classList.remove('hidden');scrollTo(0,0)}
function mode(m){authMode=m;$('loginTab').classList.toggle('active',m==='login');$('regTab').classList.toggle('active',m==='register');$('authSubmit').textContent=m==='login'?'Login':'Create Account'}
async function init(){let s=(await db.auth.getSession()).data.session;user=s?.user||null;nav();let p=location.pathname.split('/').filter(Boolean),i=p.indexOf('c');if(i>=0&&p[i+1])loadPublic(decodeURIComponent(p[i+1]))}
function nav(){$('authBtn').classList.toggle('hidden',!!user);$('dashBtn').classList.toggle('hidden',!user);$('logoutBtn').classList.toggle('hidden',!user)}
$('authForm').onsubmit=async e=>{e.preventDefault();$('authMsg').textContent='Please wait...';let r=authMode==='login'?await db.auth.signInWithPassword({email:$('email').value,password:$('password').value}):await db.auth.signUp({email:$('email').value,password:$('password').value});if(r.error){$('authMsg').textContent='❌ '+r.error.message;return}if(!r.data.session){$('authMsg').textContent='✅ Account created. Email confirmation करें।';return}user=r.data.user||r.data.session.user;nav();dashboard()};
async function logout(){await db.auth.signOut();user=null;coaching=null;nav();show('home')}
async function dashboard(){if(!user)return show('auth');show('dash');let r=await db.from('coachings').select('*').eq('owner_id',user.id).maybeSingle();coaching=r.data||null;if(coaching){for(let [id,v] of Object.entries({coachingName:coaching.coaching_name,slug:coaching.slug,description:coaching.description,founderName:coaching.founder_name,designation:coaching.founder_designation,phone:coaching.phone,contactEmail:coaching.email,address:coaching.address}))$(id).value=v||'';if(coaching.logo_url){$('logoPreview').src=coaching.logo_url;$('logoPreview').classList.remove('hidden')}if(coaching.founder_photo_url){$('founderPreview').src=coaching.founder_photo_url;$('founderPreview').classList.remove('hidden')}link();batches()}else{$('batches').textContent='पहले Coaching Save करें।'}}
function preview(file,id){if(file){$(id).src=URL.createObjectURL(file);$(id).classList.remove('hidden')}}$('logo').onchange=e=>preview(e.target.files[0],'logoPreview');$('founderPhoto').onchange=e=>preview(e.target.files[0],'founderPreview');
async function upload(f,type){if(!f)return null;let path=`${user.id}/${type}-${Date.now()}-${f.name}`;let r=await db.storage.from('coaching-images').upload(path,f);if(r.error)throw r.error;return db.storage.from('coaching-images').getPublicUrl(path).data.publicUrl}
$('coachingForm').onsubmit=async e=>{e.preventDefault();try{$('saveMsg').textContent='Saving...';let logo=coaching?.logo_url||null,photo=coaching?.founder_photo_url||null;if($('logo').files[0])logo=await upload($('logo').files[0],'logo');if($('founderPhoto').files[0])photo=await upload($('founderPhoto').files[0],'founder');let slug=$('slug').value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');let x={owner_id:user.id,coaching_name:$('coachingName').value,slug,description:$('description').value,logo_url:logo,founder_name:$('founderName').value,founder_designation:$('designation').value||'Director',founder_photo_url:photo,phone:$('phone').value,email:$('contactEmail').value,address:$('address').value,updated_at:new Date().toISOString()};let r=coaching?await db.from('coachings').update(x).eq('id',coaching.id).select().single():await db.from('coachings').insert(x).select().single();if(r.error)throw r.error;coaching=r.data;$('saveMsg').textContent='✅ Saved!';link();batches()}catch(err){$('saveMsg').textContent='❌ '+err.message}};
function link(){let base=location.href.split('/c/')[0].replace(/\/index\.html$/,'');$('publicLink').value=base+'/c/'+coaching.slug;$('linkBox').classList.remove('hidden')}function copyLink(){navigator.clipboard.writeText($('publicLink').value);alert('Link copied!')}function openLink(){location.href=$('publicLink').value}
async function batches(){if(!coaching)return;let r=await db.from('batches').select('*').eq('coaching_id',coaching.id).order('created_at',{ascending:false});$('batches').innerHTML=(r.data||[]).map(x=>`<div class="batch-item"><span><b>${esc(x.batch_name)}</b><br><small>${esc(x.description||'')}</small></span><button onclick="delBatch('${x.id}')">🗑️</button></div>`).join('')||'अभी कोई Batch नहीं।'}async function addBatch(){if(!coaching)return alert('पहले Coaching Save करें।');if(!$('batchName').value.trim())return;let r=await db.from('batches').insert({coaching_id:coaching.id,batch_name:$('batchName').value.trim(),description:$('batchDesc').value.trim()});if(r.error)return alert(r.error.message);$('batchName').value='';$('batchDesc').value='';batches()}async function delBatch(id){await db.from('batches').delete().eq('id',id);batches()}
const esc=s=>{let d=document.createElement('div');d.textContent=s||'';return d.innerHTML};
async function loadPublic(slug){show('public');let r=await db.from('coachings').select('*').eq('slug',slug).single();if(r.error){$('publicContent').innerHTML='<div class="loading"><h1>Page Not Found</h1></div>';return}let c=r.data,b=(await db.from('batches').select('*').eq('coaching_id',c.id)).data||[];$('publicContent').innerHTML=`<div class="public-hero">${c.logo_url?`<img class="public-logo" src="${c.logo_url}">`:'🎓'}<div><h1>${esc(c.coaching_name)}</h1><p>${esc(c.description||'')}</p></div></div><div class="public-grid"><div class="card"><h2>📚 Current Batches</h2>${b.map(x=>`<p><b>${esc(x.batch_name)}</b><br><small>${esc(x.description||'')}</small></p>`).join('')||'No batches yet.'}</div><div class="card">${c.founder_photo_url?`<img class="founder-photo" src="${c.founder_photo_url}">`:''}<h2>👨‍🏫 ${esc(c.founder_designation||'Director')}</h2><h3>${esc(c.founder_name||'')}</h3></div><div class="card"><h2>📞 Contact Details</h2><p>📍 ${esc(c.address||'')}</p><p>📱 ${esc(c.phone||'')}</p><p>✉️ ${esc(c.email||'')}</p></div></div><a class="student" href="https://portal.greatindia.technology/">🎓 STUDENT LOGIN / REGISTER</a>`}
init();
